# Generated by Django 4.2.8 on 2024-01-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cname',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Child', 'Child')], default='Men', max_length=100),
        ),
    ]
