# Generated by Django 4.2.8 on 2024-01-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_cname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
