# Generated by Django 4.2.8 on 2024-01-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Child', 'Child')], default='Men', max_length=100)),
                ('bname', models.CharField(choices=[('Levis', 'Levis'), ('Gap', 'Gap'), ('Tommy', 'Tommy')], default='Levis', max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('si', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=100)),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('pimage', models.ImageField(default='', upload_to='productimage/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
